// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hjzsdxrgzbqwtdgdqkbz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhqenNkeHJnemJxd3RkZ2Rxa2J6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5MDM0OTMsImV4cCI6MjA2OTQ3OTQ5M30.caZTG5cpQvnImr7Waq-zpikChyAxsJj9ZysmNMHOqqs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});